/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Buku;
import controller.Perpustakaan;
import model.Siswa;

/**
 *
 * @author ini laptop
 */
public class Menu extends javax.swing.JFrame {
    CardLayout cl;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Input
     */
    public Menu() {
        initComponents();
        cl = (CardLayout) (fieldCardPanel.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        salute = new javax.swing.JLabel();
        fieldCardPanel = new javax.swing.JPanel();
        inputBukuPanel = new javax.swing.JPanel();
        kodePanel = new javax.swing.JPanel();
        kodeField = new javax.swing.JTextField();
        kodeLabel = new javax.swing.JLabel();
        judulPanel = new javax.swing.JPanel();
        judulField = new javax.swing.JTextField();
        judulLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        registerBukuButton = new javax.swing.JButton();
        jenisPanel = new javax.swing.JPanel();
        jenisLabel = new javax.swing.JLabel();
        jenisField = new javax.swing.JTextField();
        inputSiswaPanel = new javax.swing.JPanel();
        nisPanel = new javax.swing.JPanel();
        nisField = new javax.swing.JTextField();
        nisLabel = new javax.swing.JLabel();
        namaPanel = new javax.swing.JPanel();
        namaField = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        alamatPanel = new javax.swing.JPanel();
        alamatLabel = new javax.swing.JLabel();
        alamatField = new javax.swing.JTextField();
        buttonPanel1 = new javax.swing.JPanel();
        registerSiswaButton = new javax.swing.JButton();
        lihatBukuPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bukuTable = new javax.swing.JTable();
        lihatSiswaPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        siswaTable = new javax.swing.JTable();
        pinjamBukuPanel = new javax.swing.JPanel();
        nisPinjamPanel = new javax.swing.JPanel();
        nisPinjamField = new javax.swing.JTextField();
        nisPinjamLabel = new javax.swing.JLabel();
        kodeBukuPanel = new javax.swing.JPanel();
        kodeBukuLabel = new javax.swing.JLabel();
        kodeBukuField = new javax.swing.JTextField();
        buttonPanel2 = new javax.swing.JPanel();
        bookBorrowButton = new javax.swing.JButton();
        dmyPinjamPanel = new javax.swing.JPanel();
        dmyPinjamLabel = new javax.swing.JLabel();
        datePinjamPanel = new javax.swing.JPanel();
        datePinjamLabel = new javax.swing.JLabel();
        datePinjamField = new javax.swing.JTextField();
        monthPinjamPanel = new javax.swing.JPanel();
        monthPinjamLabel = new javax.swing.JLabel();
        monthPinjamField = new javax.swing.JTextField();
        yearPinjamPanel = new javax.swing.JPanel();
        yearPinjamLabel = new javax.swing.JLabel();
        yearPinjamField = new javax.swing.JTextField();
        dmyKembaliPanel = new javax.swing.JPanel();
        dmyKembaliLabel = new javax.swing.JLabel();
        dateKembaliPanel = new javax.swing.JPanel();
        dateKembaliLabel = new javax.swing.JLabel();
        dateKembaliField = new javax.swing.JTextField();
        monthKembaliPanel = new javax.swing.JPanel();
        monthKembaliLabel = new javax.swing.JLabel();
        monthKembaliField = new javax.swing.JTextField();
        yearKembaliPanel = new javax.swing.JPanel();
        yearKembaliLabel = new javax.swing.JLabel();
        yearKembaliField = new javax.swing.JTextField();
        kodeTransaksiPanel = new javax.swing.JPanel();
        kodeTransaksiField = new javax.swing.JTextField();
        kodeTransaksiLabel = new javax.swing.JLabel();
        kembalikanBukuPanel = new javax.swing.JPanel();
        buttonPanel3 = new javax.swing.JPanel();
        bookBorrowButton2 = new javax.swing.JButton();
        kodeTransaksiPanel1 = new javax.swing.JPanel();
        kodeTransaksiField1 = new javax.swing.JTextField();
        kodeTransaksiLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Input Buku");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Input Siswa");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Lihat Buku");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Lihat Siswa");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Pinjam Buku");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Kembalikan Buku");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        salute.setText(String.format("Halo, %s!", username));
        salute.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salute)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(salute))
        );

        fieldCardPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fieldCardPanel.setLayout(new java.awt.CardLayout());

        kodeLabel.setText("Kode");

        javax.swing.GroupLayout kodePanelLayout = new javax.swing.GroupLayout(kodePanel);
        kodePanel.setLayout(kodePanelLayout);
        kodePanelLayout.setHorizontalGroup(
            kodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kodePanelLayout.createSequentialGroup()
                .addGroup(kodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodeField)
                    .addGroup(kodePanelLayout.createSequentialGroup()
                        .addComponent(kodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kodePanelLayout.setVerticalGroup(
            kodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kodePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        judulLabel.setText("Judul");

        javax.swing.GroupLayout judulPanelLayout = new javax.swing.GroupLayout(judulPanel);
        judulPanel.setLayout(judulPanelLayout);
        judulPanelLayout.setHorizontalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judulPanelLayout.createSequentialGroup()
                .addGroup(judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulField, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(judulPanelLayout.createSequentialGroup()
                        .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        judulPanelLayout.setVerticalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, judulPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judulField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        registerBukuButton.setText("Daftar");
        registerBukuButton.addActionListener(this::registerBukuButtonActionPerformed);

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addComponent(registerBukuButton)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerBukuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jenisLabel.setText("Jenis");

        jenisField.addActionListener(this::jenisFieldActionPerformed);

        javax.swing.GroupLayout jenisPanelLayout = new javax.swing.GroupLayout(jenisPanel);
        jenisPanel.setLayout(jenisPanelLayout);
        jenisPanelLayout.setHorizontalGroup(
            jenisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisPanelLayout.createSequentialGroup()
                .addGroup(jenisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jenisPanelLayout.createSequentialGroup()
                        .addComponent(jenisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jenisField))
                .addContainerGap())
        );
        jenisPanelLayout.setVerticalGroup(
            jenisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jenisPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jenisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout inputBukuPanelLayout = new javax.swing.GroupLayout(inputBukuPanel);
        inputBukuPanel.setLayout(inputBukuPanelLayout);
        inputBukuPanelLayout.setHorizontalGroup(
            inputBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputBukuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(judulPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kodePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jenisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        inputBukuPanelLayout.setVerticalGroup(
            inputBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputBukuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fieldCardPanel.add(inputBukuPanel, "inputBukuCard");

        nisLabel.setText("NIS");

        javax.swing.GroupLayout nisPanelLayout = new javax.swing.GroupLayout(nisPanel);
        nisPanel.setLayout(nisPanelLayout);
        nisPanelLayout.setHorizontalGroup(
            nisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nisPanelLayout.createSequentialGroup()
                .addGroup(nisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nisField)
                    .addGroup(nisPanelLayout.createSequentialGroup()
                        .addComponent(nisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nisPanelLayout.setVerticalGroup(
            nisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        namaLabel.setText("Nama");

        javax.swing.GroupLayout namaPanelLayout = new javax.swing.GroupLayout(namaPanel);
        namaPanel.setLayout(namaPanelLayout);
        namaPanelLayout.setHorizontalGroup(
            namaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPanelLayout.createSequentialGroup()
                .addGroup(namaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaField, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(namaPanelLayout.createSequentialGroup()
                        .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        namaPanelLayout.setVerticalGroup(
            namaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        alamatLabel.setText("Alamat");

        javax.swing.GroupLayout alamatPanelLayout = new javax.swing.GroupLayout(alamatPanel);
        alamatPanel.setLayout(alamatPanelLayout);
        alamatPanelLayout.setHorizontalGroup(
            alamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatPanelLayout.createSequentialGroup()
                .addGroup(alamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alamatPanelLayout.createSequentialGroup()
                        .addComponent(alamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(alamatField))
                .addContainerGap())
        );
        alamatPanelLayout.setVerticalGroup(
            alamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alamatPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alamatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        registerSiswaButton.setText("Daftar");
        registerSiswaButton.addActionListener(this::registerSiswaButtonActionPerformed);

        javax.swing.GroupLayout buttonPanel1Layout = new javax.swing.GroupLayout(buttonPanel1);
        buttonPanel1.setLayout(buttonPanel1Layout);
        buttonPanel1Layout.setHorizontalGroup(
            buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerSiswaButton)
                .addContainerGap())
        );
        buttonPanel1Layout.setVerticalGroup(
            buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerSiswaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout inputSiswaPanelLayout = new javax.swing.GroupLayout(inputSiswaPanel);
        inputSiswaPanel.setLayout(inputSiswaPanelLayout);
        inputSiswaPanelLayout.setHorizontalGroup(
            inputSiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputSiswaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputSiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nisPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alamatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        inputSiswaPanelLayout.setVerticalGroup(
            inputSiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputSiswaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(buttonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fieldCardPanel.add(inputSiswaPanel, "inputSiswaCard");

        bukuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Buku", "Judul", "Jenis"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bukuTable);

        javax.swing.GroupLayout lihatBukuPanelLayout = new javax.swing.GroupLayout(lihatBukuPanel);
        lihatBukuPanel.setLayout(lihatBukuPanelLayout);
        lihatBukuPanelLayout.setHorizontalGroup(
            lihatBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        lihatBukuPanelLayout.setVerticalGroup(
            lihatBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        fieldCardPanel.add(lihatBukuPanel, "lihatBukuCard");

        siswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(siswaTable);

        javax.swing.GroupLayout lihatSiswaPanelLayout = new javax.swing.GroupLayout(lihatSiswaPanel);
        lihatSiswaPanel.setLayout(lihatSiswaPanelLayout);
        lihatSiswaPanelLayout.setHorizontalGroup(
            lihatSiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        lihatSiswaPanelLayout.setVerticalGroup(
            lihatSiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        fieldCardPanel.add(lihatSiswaPanel, "lihatSiswaCard");

        nisPinjamLabel.setText("NIS");

        javax.swing.GroupLayout nisPinjamPanelLayout = new javax.swing.GroupLayout(nisPinjamPanel);
        nisPinjamPanel.setLayout(nisPinjamPanelLayout);
        nisPinjamPanelLayout.setHorizontalGroup(
            nisPinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nisPinjamPanelLayout.createSequentialGroup()
                .addGroup(nisPinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nisPinjamField, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(nisPinjamPanelLayout.createSequentialGroup()
                        .addComponent(nisPinjamLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nisPinjamPanelLayout.setVerticalGroup(
            nisPinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nisPinjamPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nisPinjamLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nisPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        kodeBukuLabel.setText("Kode Buku");

        javax.swing.GroupLayout kodeBukuPanelLayout = new javax.swing.GroupLayout(kodeBukuPanel);
        kodeBukuPanel.setLayout(kodeBukuPanelLayout);
        kodeBukuPanelLayout.setHorizontalGroup(
            kodeBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kodeBukuPanelLayout.createSequentialGroup()
                .addGroup(kodeBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodeBukuField, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(kodeBukuPanelLayout.createSequentialGroup()
                        .addComponent(kodeBukuLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kodeBukuPanelLayout.setVerticalGroup(
            kodeBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kodeBukuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kodeBukuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodeBukuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        bookBorrowButton.setText("Pinjam");
        bookBorrowButton.addActionListener(this::bookBorrowButtonActionPerformed);

        javax.swing.GroupLayout buttonPanel2Layout = new javax.swing.GroupLayout(buttonPanel2);
        buttonPanel2.setLayout(buttonPanel2Layout);
        buttonPanel2Layout.setHorizontalGroup(
            buttonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookBorrowButton)
                .addContainerGap())
        );
        buttonPanel2Layout.setVerticalGroup(
            buttonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookBorrowButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dmyPinjamLabel.setText("Tanggal Pinjam");

        datePinjamLabel.setText("Tanggal");

        datePinjamField.addActionListener(this::datePinjamFieldActionPerformed);

        javax.swing.GroupLayout datePinjamPanelLayout = new javax.swing.GroupLayout(datePinjamPanel);
        datePinjamPanel.setLayout(datePinjamPanelLayout);
        datePinjamPanelLayout.setHorizontalGroup(
            datePinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(datePinjamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(datePinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        datePinjamPanelLayout.setVerticalGroup(
            datePinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePinjamPanelLayout.createSequentialGroup()
                .addComponent(datePinjamLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datePinjamField)
                .addContainerGap())
        );

        monthPinjamLabel.setText("Bulan");

        javax.swing.GroupLayout monthPinjamPanelLayout = new javax.swing.GroupLayout(monthPinjamPanel);
        monthPinjamPanel.setLayout(monthPinjamPanelLayout);
        monthPinjamPanelLayout.setHorizontalGroup(
            monthPinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monthPinjamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(monthPinjamPanelLayout.createSequentialGroup()
                .addComponent(monthPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        monthPinjamPanelLayout.setVerticalGroup(
            monthPinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthPinjamPanelLayout.createSequentialGroup()
                .addComponent(monthPinjamLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthPinjamField))
        );

        yearPinjamLabel.setText("Tahun");

        javax.swing.GroupLayout yearPinjamPanelLayout = new javax.swing.GroupLayout(yearPinjamPanel);
        yearPinjamPanel.setLayout(yearPinjamPanelLayout);
        yearPinjamPanelLayout.setHorizontalGroup(
            yearPinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yearPinjamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(yearPinjamPanelLayout.createSequentialGroup()
                .addComponent(yearPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        yearPinjamPanelLayout.setVerticalGroup(
            yearPinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yearPinjamPanelLayout.createSequentialGroup()
                .addComponent(yearPinjamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearPinjamField)
                .addContainerGap())
        );

        javax.swing.GroupLayout dmyPinjamPanelLayout = new javax.swing.GroupLayout(dmyPinjamPanel);
        dmyPinjamPanel.setLayout(dmyPinjamPanelLayout);
        dmyPinjamPanelLayout.setHorizontalGroup(
            dmyPinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dmyPinjamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dmyPinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dmyPinjamLabel)
                    .addGroup(dmyPinjamPanelLayout.createSequentialGroup()
                        .addComponent(datePinjamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthPinjamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearPinjamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        dmyPinjamPanelLayout.setVerticalGroup(
            dmyPinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dmyPinjamPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dmyPinjamLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dmyPinjamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datePinjamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthPinjamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearPinjamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        dmyKembaliLabel.setText("Tanggal Kembali");

        dateKembaliLabel.setText("Tanggal");

        dateKembaliField.addActionListener(this::dateKembaliFieldActionPerformed);

        javax.swing.GroupLayout dateKembaliPanelLayout = new javax.swing.GroupLayout(dateKembaliPanel);
        dateKembaliPanel.setLayout(dateKembaliPanelLayout);
        dateKembaliPanelLayout.setHorizontalGroup(
            dateKembaliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dateKembaliLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dateKembaliField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        dateKembaliPanelLayout.setVerticalGroup(
            dateKembaliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateKembaliPanelLayout.createSequentialGroup()
                .addComponent(dateKembaliLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateKembaliField)
                .addContainerGap())
        );

        monthKembaliLabel.setText("Bulan");

        monthKembaliField.addActionListener(this::monthKembaliFieldActionPerformed);

        javax.swing.GroupLayout monthKembaliPanelLayout = new javax.swing.GroupLayout(monthKembaliPanel);
        monthKembaliPanel.setLayout(monthKembaliPanelLayout);
        monthKembaliPanelLayout.setHorizontalGroup(
            monthKembaliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monthKembaliLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(monthKembaliPanelLayout.createSequentialGroup()
                .addComponent(monthKembaliField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        monthKembaliPanelLayout.setVerticalGroup(
            monthKembaliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthKembaliPanelLayout.createSequentialGroup()
                .addComponent(monthKembaliLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthKembaliField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        yearKembaliLabel.setText("Tahun");

        javax.swing.GroupLayout yearKembaliPanelLayout = new javax.swing.GroupLayout(yearKembaliPanel);
        yearKembaliPanel.setLayout(yearKembaliPanelLayout);
        yearKembaliPanelLayout.setHorizontalGroup(
            yearKembaliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yearKembaliLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(yearKembaliPanelLayout.createSequentialGroup()
                .addComponent(yearKembaliField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        yearKembaliPanelLayout.setVerticalGroup(
            yearKembaliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yearKembaliPanelLayout.createSequentialGroup()
                .addComponent(yearKembaliLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearKembaliField)
                .addContainerGap())
        );

        javax.swing.GroupLayout dmyKembaliPanelLayout = new javax.swing.GroupLayout(dmyKembaliPanel);
        dmyKembaliPanel.setLayout(dmyKembaliPanelLayout);
        dmyKembaliPanelLayout.setHorizontalGroup(
            dmyKembaliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dmyKembaliPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dmyKembaliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dmyKembaliLabel)
                    .addGroup(dmyKembaliPanelLayout.createSequentialGroup()
                        .addComponent(dateKembaliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthKembaliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearKembaliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dmyKembaliPanelLayout.setVerticalGroup(
            dmyKembaliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dmyKembaliPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dmyKembaliLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dmyKembaliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateKembaliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthKembaliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearKembaliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        kodeTransaksiLabel.setText("Kode Transaksi");

        javax.swing.GroupLayout kodeTransaksiPanelLayout = new javax.swing.GroupLayout(kodeTransaksiPanel);
        kodeTransaksiPanel.setLayout(kodeTransaksiPanelLayout);
        kodeTransaksiPanelLayout.setHorizontalGroup(
            kodeTransaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kodeTransaksiPanelLayout.createSequentialGroup()
                .addGroup(kodeTransaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodeTransaksiField, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(kodeTransaksiPanelLayout.createSequentialGroup()
                        .addComponent(kodeTransaksiLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kodeTransaksiPanelLayout.setVerticalGroup(
            kodeTransaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kodeTransaksiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kodeTransaksiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodeTransaksiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pinjamBukuPanelLayout = new javax.swing.GroupLayout(pinjamBukuPanel);
        pinjamBukuPanel.setLayout(pinjamBukuPanelLayout);
        pinjamBukuPanelLayout.setHorizontalGroup(
            pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinjamBukuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nisPinjamPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kodeBukuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pinjamBukuPanelLayout.createSequentialGroup()
                        .addComponent(dmyPinjamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dmyKembaliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(kodeTransaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pinjamBukuPanelLayout.setVerticalGroup(
            pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinjamBukuPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(kodeTransaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nisPinjamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodeBukuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinjamBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dmyPinjamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dmyKembaliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(buttonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fieldCardPanel.add(pinjamBukuPanel, "pinjamBukuCard");

        bookBorrowButton2.setText("Kembalikan");
        bookBorrowButton2.addActionListener(this::bookBorrowButton2ActionPerformed);

        javax.swing.GroupLayout buttonPanel3Layout = new javax.swing.GroupLayout(buttonPanel3);
        buttonPanel3.setLayout(buttonPanel3Layout);
        buttonPanel3Layout.setHorizontalGroup(
            buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookBorrowButton2)
                .addContainerGap())
        );
        buttonPanel3Layout.setVerticalGroup(
            buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookBorrowButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kodeTransaksiLabel1.setText("Kode Transaksi");

        javax.swing.GroupLayout kodeTransaksiPanel1Layout = new javax.swing.GroupLayout(kodeTransaksiPanel1);
        kodeTransaksiPanel1.setLayout(kodeTransaksiPanel1Layout);
        kodeTransaksiPanel1Layout.setHorizontalGroup(
            kodeTransaksiPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kodeTransaksiPanel1Layout.createSequentialGroup()
                .addGroup(kodeTransaksiPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodeTransaksiField1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(kodeTransaksiPanel1Layout.createSequentialGroup()
                        .addComponent(kodeTransaksiLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kodeTransaksiPanel1Layout.setVerticalGroup(
            kodeTransaksiPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kodeTransaksiPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kodeTransaksiLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodeTransaksiField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout kembalikanBukuPanelLayout = new javax.swing.GroupLayout(kembalikanBukuPanel);
        kembalikanBukuPanel.setLayout(kembalikanBukuPanelLayout);
        kembalikanBukuPanelLayout.setHorizontalGroup(
            kembalikanBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kembalikanBukuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kembalikanBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kodeTransaksiPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kembalikanBukuPanelLayout.setVerticalGroup(
            kembalikanBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kembalikanBukuPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(kodeTransaksiPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254)
                .addComponent(buttonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fieldCardPanel.add(kembalikanBukuPanel, "kembalikanBukuCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        cl.show(fieldCardPanel, "inputBukuCard");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void registerBukuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBukuButtonActionPerformed
        String kode = kodeField.getText();
        String judul = judulField.getText();
        String jenis = jenisField.getText();
        
        if(kode.equals("") || judul.equals("") || jenis.equals("")){
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
        } else{
            Perpustakaan.inputBuku(judul, kode, jenis);
            JOptionPane.showMessageDialog(this, "Input buku berhasil!");
            kodeField.setText("");
            judulField.setText("");
            jenisField.setText("");
        }
    }//GEN-LAST:event_registerBukuButtonActionPerformed

    private void registerSiswaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerSiswaButtonActionPerformed
        String nis = nisField.getText();
        String nama = namaField.getText();
        String alamat = alamatField.getText();
        
        if(nis.equals("") || nama.equals("") || alamat.equals("")){
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
        } else{
            Perpustakaan.inputSiswa(nis, nama, alamat);
            JOptionPane.showMessageDialog(this, "Input siswa berhasil!");
            nisField.setText("");
            namaField.setText("");
            alamatField.setText("");
        }
    }//GEN-LAST:event_registerSiswaButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cl.show(fieldCardPanel, "inputSiswaCard");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) bukuTable.getModel();
        dtm.setRowCount(0);
        String filePath = "src/main/resources/buku.txt";
        try(BufferedReader br = new BufferedReader(new FileReader(filePath))){
            String line;
            while((line = br.readLine()) != null){
                String[] data = line.split(" - ");
                dtm.addRow(data);
            }
        } catch (FileNotFoundException ex) {
            System.getLogger(Menu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (IOException ex) {
            System.getLogger(Menu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        cl.show(fieldCardPanel, "lihatBukuCard");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) siswaTable.getModel();
        dtm.setRowCount(0);
        String filePath = "src/main/resources/siswa.txt";
        try(BufferedReader br = new BufferedReader(new FileReader(filePath))){
            String line;
            while((line = br.readLine()) != null){
                String[] data = line.split(" - ");
                dtm.addRow(data);
            }
        } catch (FileNotFoundException ex) {
            System.getLogger(Menu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (IOException ex) {
            System.getLogger(Menu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        cl.show(fieldCardPanel, "lihatSiswaCard");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        cl.show(fieldCardPanel, "pinjamBukuCard");
        datePinjamField.setText(String.format("%d", LocalDateTime.now().getDayOfMonth()));
        monthPinjamField.setText(String.format("%d", LocalDateTime.now().getMonthValue()));
        yearPinjamField.setText(String.format("%d", LocalDateTime.now().getYear()));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        cl.show(fieldCardPanel, "kembalikanBukuCard");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jenisFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisFieldActionPerformed

    private void bookBorrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBorrowButtonActionPerformed
        String kodeTransaksi = kodeTransaksiField.getText();
        String nis = nisPinjamField.getText();
        String kodeBuku = kodeBukuField.getText();
        String tglPinjam = String.format("%s/%s/%s", datePinjamField.getText(), monthPinjamField.getText(), yearPinjamField.getText());
        String tglKembali = String.format("%s/%s/%s", dateKembaliField.getText(), monthKembaliField.getText(), yearKembaliField.getText());
        
        if(nis.equalsIgnoreCase("")  || kodeBuku.equalsIgnoreCase("") || tglPinjam.equalsIgnoreCase("") || tglKembali.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");    
        } else{
            Perpustakaan.pinjam(kodeTransaksi, nis, kodeBuku, tglPinjam, tglKembali, username);
            JOptionPane.showMessageDialog(this, "Peminjaman berhasil!");
        }
        datePinjamField.setText(String.format("%d", LocalDateTime.now().getDayOfMonth()));
        monthPinjamField.setText(String.format("%d", LocalDateTime.now().getMonthValue()));
        yearPinjamField.setText(String.format("%d", LocalDateTime.now().getYear()));
        dateKembaliField.setText("");
        monthKembaliField.setText("");
        yearKembaliField.setText("");
    }//GEN-LAST:event_bookBorrowButtonActionPerformed

    private void bookBorrowButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBorrowButton2ActionPerformed
        String kodeTransaksi = kodeTransaksiField1.getText();       
        String date = String.format("%d/%d/%d", LocalDateTime.now().getDayOfMonth(), LocalDateTime.now().getMonthValue(), LocalDateTime.now().getYear());
        
        if(kodeTransaksi.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
        } else{
            Perpustakaan.kembali(kodeTransaksi, date);
        }
        kodeTransaksiField1.setText("");
        
    }//GEN-LAST:event_bookBorrowButton2ActionPerformed

    private void monthKembaliFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthKembaliFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthKembaliFieldActionPerformed

    private void dateKembaliFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateKembaliFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateKembaliFieldActionPerformed

    private void datePinjamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePinjamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datePinjamFieldActionPerformed

    
    String getUsername(){
        String[] data = null;
        String nip = Login.getNip();
        String filepath = "src/main/resources/pegawai.txt";
        try(BufferedReader br = new BufferedReader(new FileReader(filepath))){
            String line;
            while((line = br.readLine()) != null){
                data = line.split(" - "); 
                if(data.length >= 3){
                    if(data[0].equals(nip)) {
                        return data[1];
                    }
                }
            }                         
        } catch (FileNotFoundException ex) {
            System.getLogger(Menu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (IOException ex) {
            System.getLogger(Menu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        return "admin";
    }
    String username = getUsername();
    /**
     * @param args the command line arguments
     */    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatField;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JPanel alamatPanel;
    private javax.swing.JButton bookBorrowButton;
    private javax.swing.JButton bookBorrowButton2;
    private javax.swing.JTable bukuTable;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel buttonPanel1;
    private javax.swing.JPanel buttonPanel2;
    private javax.swing.JPanel buttonPanel3;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JTextField dateKembaliField;
    private javax.swing.JLabel dateKembaliLabel;
    private javax.swing.JPanel dateKembaliPanel;
    private javax.swing.JTextField datePinjamField;
    private javax.swing.JLabel datePinjamLabel;
    private javax.swing.JPanel datePinjamPanel;
    private javax.swing.JLabel dmyKembaliLabel;
    private javax.swing.JPanel dmyKembaliPanel;
    private javax.swing.JLabel dmyPinjamLabel;
    private javax.swing.JPanel dmyPinjamPanel;
    private javax.swing.JPanel fieldCardPanel;
    private javax.swing.JPanel inputBukuPanel;
    private javax.swing.JPanel inputSiswaPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jenisField;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JPanel jenisPanel;
    private javax.swing.JTextField judulField;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JPanel judulPanel;
    private javax.swing.JPanel kembalikanBukuPanel;
    private javax.swing.JTextField kodeBukuField;
    private javax.swing.JLabel kodeBukuLabel;
    private javax.swing.JPanel kodeBukuPanel;
    private javax.swing.JTextField kodeField;
    private javax.swing.JLabel kodeLabel;
    private javax.swing.JPanel kodePanel;
    private javax.swing.JTextField kodeTransaksiField;
    private javax.swing.JTextField kodeTransaksiField1;
    private javax.swing.JLabel kodeTransaksiLabel;
    private javax.swing.JLabel kodeTransaksiLabel1;
    private javax.swing.JPanel kodeTransaksiPanel;
    private javax.swing.JPanel kodeTransaksiPanel1;
    private javax.swing.JPanel lihatBukuPanel;
    private javax.swing.JPanel lihatSiswaPanel;
    private javax.swing.JTextField monthKembaliField;
    private javax.swing.JLabel monthKembaliLabel;
    private javax.swing.JPanel monthKembaliPanel;
    private javax.swing.JTextField monthPinjamField;
    private javax.swing.JLabel monthPinjamLabel;
    private javax.swing.JPanel monthPinjamPanel;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JPanel namaPanel;
    private javax.swing.JTextField nisField;
    private javax.swing.JLabel nisLabel;
    private javax.swing.JPanel nisPanel;
    private javax.swing.JTextField nisPinjamField;
    private javax.swing.JLabel nisPinjamLabel;
    private javax.swing.JPanel nisPinjamPanel;
    private javax.swing.JPanel pinjamBukuPanel;
    private javax.swing.JButton registerBukuButton;
    private javax.swing.JButton registerSiswaButton;
    private javax.swing.JLabel salute;
    private javax.swing.JTable siswaTable;
    private javax.swing.JTextField yearKembaliField;
    private javax.swing.JLabel yearKembaliLabel;
    private javax.swing.JPanel yearKembaliPanel;
    private javax.swing.JTextField yearPinjamField;
    private javax.swing.JLabel yearPinjamLabel;
    private javax.swing.JPanel yearPinjamPanel;
    // End of variables declaration//GEN-END:variables
}
